import type { Scenario } from '@/engine/types';

// Scenario 01 — The Canadian Launch (Moomoo). Consumer-facing PM.

export const scenario01: Scenario = {
  id: '01-canadian-launch',
  name: 'The Canadian Launch — Moomoo',
  summary:
    'Senior PM for Moomoo Canada mobile app. Hit 100K Canadian traders this quarter without tripping CIRO or breaking HQ trust.',
  totalIterations: 6,
  targetRevenue: 5000,

  customers: [
    {
      id: 'maya',
      name: 'Maya (New Canadian Investor)',
      archetype: 'mainstream',
      engagementState: 'interested',
      happiness: 5,
      ltv: 850,
      lastFullRelease: null,
      consecutivePartial: 0,
      consecutiveNothing: 0,
    },
    {
      id: 'darren',
      name: 'Darren (Active Trader)',
      archetype: 'power-user',
      engagementState: 'active',
      happiness: 4,
      ltv: 3200,
      lastFullRelease: null,
      consecutivePartial: 0,
      consecutiveNothing: 0,
    },
    {
      id: 'priya',
      name: 'Priya (Aspiring Investor)',
      archetype: 'innovator',
      engagementState: 'dormant',
      happiness: 4,
      ltv: 400,
      lastFullRelease: null,
      consecutivePartial: 0,
      consecutiveNothing: 0,
    },
  ],

  stakeholders: [
    { id: 'hq', name: 'Wei (HQ Growth VP)', role: 'Leadership', trust: 6, lastInteraction: 0 },
    { id: 'ciro', name: 'Aisha (CIRO Compliance)', role: 'Compliance', trust: 8, lastInteraction: 0 },
  ],

  team: {
    morale: 5,
    headcount: 6,
    onboarding: 0,
    sickOrVacation: 0,
    burnoutFlag: false,
  },

  tech: {
    releaseCost: 3,
    capacityBaseline: 15,
    capacityVariance: 3,
    techDebt: 35,
    reliability: 6,
    cycleTime: 1.0,
    investmentsDone: [],
    lastTechInvestmentIter: null,
  },

  economy: {
    revenue: 0,
    interestAccrued: 0,
    budgetRemaining: 500_000,
    interestRate: 0,
  },

  initialBacklog: [
    {
      id: 'tfsa',
      title: 'TFSA Account Support',
      kind: 'customer',
      effort: 10,
      effortRevealed: 10,
      value: 1000,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'tfsa',
    },
    {
      id: 'rrsp',
      title: 'RRSP Account Support',
      kind: 'customer',
      effort: 12,
      effortRevealed: 12,
      value: 700,
      satisfies: ['maya'],
      requires: [],
      productId: 'rrsp',
    },
    {
      id: 'fractional-shares',
      title: 'Fractional Shares (US equities)',
      kind: 'customer',
      effort: 6,
      effortRevealed: 6,
      value: 600,
      satisfies: ['priya'],
      requires: [],
      productId: 'fractional-shares',
    },
    {
      id: 'level2-data',
      title: 'Level 2 US Market Data (free tier)',
      kind: 'customer',
      effort: 4,
      effortRevealed: 4,
      value: 500,
      satisfies: ['darren'],
      requires: [],
      productId: 'level2-data',
    },
    {
      id: 'us-options',
      title: 'US Options Trading (w/ Canadian tax)',
      kind: 'customer',
      effort: 14,
      effortRevealed: null,
      effortUncertain: true,
      value: 1200,
      satisfies: ['darren'],
      requires: [],
      productId: 'us-options',
    },
    {
      id: 'social-feed',
      title: 'Canadian Social Feed (localized)',
      kind: 'customer',
      effort: 8,
      effortRevealed: 8,
      value: 400,
      satisfies: ['priya'],
      requires: [],
      productId: 'social-feed',
    },
    {
      id: 'premarket-hours',
      title: 'Pre-Market & Extended Hours',
      kind: 'customer',
      effort: 7,
      effortRevealed: 7,
      value: 400,
      satisfies: ['darren'],
      requires: [],
      productId: 'premarket-hours',
    },
    {
      id: 'cad-priority',
      title: 'CAD-Priority Display Toggle',
      kind: 'customer',
      effort: 3,
      effortRevealed: 3,
      value: 250,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'cad-priority',
    },
    {
      id: 'onboarding-flow',
      title: 'Beginner Onboarding (Canadian)',
      kind: 'customer',
      effort: 5,
      effortRevealed: 5,
      value: 500,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'onboarding-flow',
    },
    {
      id: 'referral',
      title: 'Referral Program (CA$ bonus)',
      kind: 'customer',
      effort: 5,
      effortRevealed: 5,
      value: 600,
      satisfies: ['maya', 'darren', 'priya'],
      requires: [],
      productId: 'referral',
    },
    {
      id: 'feature-flags',
      title: 'Per-Geo Feature Flag Infrastructure',
      kind: 'tech',
      effort: 4,
      effortRevealed: 4,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'feature-flags',
    },
    {
      id: 'kyc-rebuild',
      title: 'Canadian KYC Pipeline Rebuild',
      kind: 'tech',
      effort: 8,
      effortRevealed: 8,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'kyc-rebuild',
    },
    {
      id: 'automated-tests',
      title: 'Automated Test Suite',
      kind: 'tech',
      effort: 5,
      effortRevealed: 5,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'automated-tests',
    },
  ],

  eventDeck: [
    {
      id: 'wei-crypto-demand',
      category: 'stakeholder',
      baseWeight: 0,
      trigger: 'forced',
      forcedAtIteration: 2,
      narrative:
        'Wei (HQ): "Launch a crypto tab by month-end." Your team has zero crypto expertise; provincial regs vary wildly.',
      options: [
        {
          id: 'accept',
          label: 'Accept and commit',
          visibleConsequence: 'HQ +2, team morale −3, tech debt +15, CIRO risk up.',
          effects: [
            { kind: 'trust', stakeholderId: 'hq', delta: 2 },
            { kind: 'morale', delta: -3 },
            { kind: 'tech-debt', delta: 15 },
          ],
        },
        {
          id: 'trade-off',
          label: 'Propose trade-off in writing',
          visibleConsequence: 'Crypto OR TFSA. HQ trust short-term −1.',
          effects: [{ kind: 'trust', stakeholderId: 'hq', delta: -1 }],
        },
        {
          id: 'defer',
          label: 'Defer with a plan',
          visibleConsequence: 'HQ trust −2, team morale +2.',
          effects: [
            { kind: 'trust', stakeholderId: 'hq', delta: -2 },
            { kind: 'morale', delta: 2 },
          ],
        },
      ],
    },
    {
      id: 'ciro-social-warning',
      category: 'regulatory',
      baseWeight: 3,
      trigger: 'weighted',
      narrative:
        'Aisha flags the social feed: "Bullish" buttons may constitute unregistered investment advice in Ontario.',
      options: [
        {
          id: 'scope-down',
          label: 'Scope feature down; remove signal buttons',
          visibleConsequence: 'CIRO trust +2. Priya disappointed.',
          effects: [
            { kind: 'trust', stakeholderId: 'ciro', delta: 2 },
            { kind: 'happiness', customerId: 'priya', delta: -1 },
          ],
        },
        {
          id: 'compliance-review',
          label: 'Full compliance review before launch',
          visibleConsequence: 'Delay 1 iteration.',
          effects: [{ kind: 'capacity-baseline', delta: -2 }],
        },
        {
          id: 'ship-anyway',
          label: 'Ship anyway — "move fast"',
          visibleConsequence: 'Big regulatory risk.',
          effects: [
            { kind: 'trust', stakeholderId: 'ciro', delta: -3 },
            { kind: 'tech-debt', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'qa-quits',
      category: 'team',
      baseWeight: 2,
      trigger: 'random',
      narrative:
        'Your QA engineer signals burnout and hints at leaving. Morale is shaky.',
      options: [
        {
          id: 'lighten-load',
          label: 'Lighten load; automate tests',
          visibleConsequence: 'Velocity short-term −2, long-term +.',
          effects: [
            { kind: 'morale', delta: 2 },
            { kind: 'capacity-baseline', delta: -1 },
          ],
        },
        {
          id: 'promote',
          label: 'Promote + raise',
          visibleConsequence: 'Morale +3. Budget hit.',
          effects: [{ kind: 'morale', delta: 3 }],
        },
        {
          id: 'ignore',
          label: 'Ignore it',
          visibleConsequence: 'Risk of quit.',
          effects: [{ kind: 'morale', delta: -2 }],
        },
      ],
    },
    {
      id: 'maya-churn-risk',
      category: 'customer',
      baseWeight: 3,
      trigger: 'weighted',
      narrative:
        'Maya has logged in twice in 3 weeks. Her survey: "No TFSA, I am moving to Wealthsimple."',
      options: [
        {
          id: 'commit-tfsa',
          label: 'Publicly commit to TFSA by iter 4',
          visibleConsequence: 'Mainstream buy-in.',
          effects: [{ kind: 'happiness', customerId: 'maya', delta: 2 }],
        },
        {
          id: 'retention-campaign',
          label: 'Retention promo instead',
          visibleConsequence: 'Temporary lift.',
          effects: [{ kind: 'happiness', customerId: 'maya', delta: 1 }],
        },
        {
          id: 'nothing',
          label: 'Do nothing',
          visibleConsequence: 'Maya churns.',
          effects: [{ kind: 'happiness', customerId: 'maya', delta: -3 }],
        },
      ],
    },
    {
      id: 'darren-reddit',
      category: 'customer',
      baseWeight: 2,
      trigger: 'random',
      narrative:
        'Darren posts on r/CanadianInvestor comparing Moomoo to IBKR. His verdict matters.',
      options: [
        {
          id: 'engage',
          label: 'PM engages publicly, acknowledges gaps',
          visibleConsequence: 'Priya interested; Darren appreciates candor.',
          effects: [
            { kind: 'happiness', customerId: 'darren', delta: 1 },
            { kind: 'happiness', customerId: 'priya', delta: 1 },
          ],
        },
        {
          id: 'deflect',
          label: 'Route to support; no comment',
          visibleConsequence: 'Opportunity missed.',
          effects: [{ kind: 'happiness', customerId: 'darren', delta: -1 }],
        },
      ],
    },
  ],
};
