import type { Scenario } from '@/engine/types';

// Scenario 01 — The Q3 Expansion (Hubflow). B2B team-collaboration SaaS PM.
// NOTE: the scenario `id` stays '01-canadian-launch' — it is a foreign key
// referenced by methods/data.ts (relatedScenarios) and the home page link.
// All PBI/customer/stakeholder/product ids are likewise load-bearing engine
// wiring and must not change; only human-readable copy is themed here.

export const scenario01: Scenario = {
  id: '01-canadian-launch',
  name: 'The Q3 Expansion — Hubflow',
  summary:
    'Senior PM for Hubflow, a B2B team-collaboration SaaS. Win the enterprise upmarket push this quarter — hit the revenue target without failing the security review or burning leadership trust.',
  totalIterations: 6,
  targetRevenue: 5000,

  customers: [
    {
      id: 'maya',
      name: 'Maya (Ops Admin, mid-market trial)',
      archetype: 'mainstream',
      engagementState: 'interested',
      happiness: 5,
      ltv: 850,
      lastFullRelease: null,
      consecutivePartial: 0,
      consecutiveNothing: 0,
    },
    {
      id: 'darren',
      name: 'Darren (Engineering Lead, power user)',
      archetype: 'power-user',
      engagementState: 'active',
      happiness: 4,
      ltv: 3200,
      lastFullRelease: null,
      consecutivePartial: 0,
      consecutiveNothing: 0,
    },
    {
      id: 'priya',
      name: 'Priya (New Trialer, evaluating)',
      archetype: 'innovator',
      engagementState: 'dormant',
      happiness: 4,
      ltv: 400,
      lastFullRelease: null,
      consecutivePartial: 0,
      consecutiveNothing: 0,
    },
  ],

  stakeholders: [
    { id: 'hq', name: 'Wei (VP of Growth)', role: 'Leadership', trust: 6, lastInteraction: 0 },
    { id: 'ciro', name: 'Aisha (Head of Platform & Security)', role: 'Security & Compliance', trust: 8, lastInteraction: 0 },
  ],

  team: {
    morale: 5,
    headcount: 6,
    onboarding: 0,
    sickOrVacation: 0,
    burnoutFlag: false,
  },

  tech: {
    releaseCost: 3,
    capacityBaseline: 15,
    capacityVariance: 3,
    techDebt: 35,
    reliability: 6,
    cycleTime: 1.0,
    investmentsDone: [],
    lastTechInvestmentIter: null,
  },

  economy: {
    revenue: 0,
    interestAccrued: 0,
    budgetRemaining: 500_000,
    interestRate: 0,
  },

  initialBacklog: [
    {
      id: 'tfsa',
      title: 'Self-Serve Team Onboarding',
      kind: 'customer',
      effort: 10,
      effortRevealed: 10,
      value: 1000,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'tfsa',
    },
    {
      id: 'rrsp',
      title: 'Admin Console & Role-Based Permissions',
      kind: 'customer',
      effort: 12,
      effortRevealed: 12,
      value: 700,
      satisfies: ['maya'],
      requires: [],
      productId: 'rrsp',
    },
    {
      id: 'fractional-shares',
      title: 'Integrations Marketplace (Slack & Jira)',
      kind: 'customer',
      effort: 6,
      effortRevealed: 6,
      value: 600,
      satisfies: ['priya'],
      requires: [],
      productId: 'fractional-shares',
    },
    {
      id: 'level2-data',
      title: 'Real-Time Analytics Dashboards',
      kind: 'customer',
      effort: 4,
      effortRevealed: 4,
      value: 500,
      satisfies: ['darren'],
      requires: [],
      productId: 'level2-data',
    },
    {
      id: 'us-options',
      title: 'Public REST API & Webhooks',
      kind: 'customer',
      effort: 14,
      effortRevealed: null,
      effortUncertain: true,
      value: 1200,
      satisfies: ['darren'],
      requires: [],
      productId: 'us-options',
    },
    {
      id: 'social-feed',
      title: 'Team Activity Feed & @Mentions',
      kind: 'customer',
      effort: 8,
      effortRevealed: 8,
      value: 400,
      satisfies: ['priya'],
      requires: [],
      productId: 'social-feed',
    },
    {
      id: 'premarket-hours',
      title: 'Mobile App (iOS & Android)',
      kind: 'customer',
      effort: 7,
      effortRevealed: 7,
      value: 400,
      satisfies: ['darren'],
      requires: [],
      productId: 'premarket-hours',
    },
    {
      id: 'cad-priority',
      title: 'Custom Workspace Branding',
      kind: 'customer',
      effort: 3,
      effortRevealed: 3,
      value: 250,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'cad-priority',
    },
    {
      id: 'onboarding-flow',
      title: 'Guided Setup Wizard (first-run)',
      kind: 'customer',
      effort: 5,
      effortRevealed: 5,
      value: 500,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'onboarding-flow',
    },
    {
      id: 'referral',
      title: 'In-App Referral Program (credit bonus)',
      kind: 'customer',
      effort: 5,
      effortRevealed: 5,
      value: 600,
      satisfies: ['maya', 'darren', 'priya'],
      requires: [],
      productId: 'referral',
    },
    {
      id: 'feature-flags',
      title: 'Per-Tenant Feature Flag Infrastructure',
      kind: 'tech',
      effort: 4,
      effortRevealed: 4,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'feature-flags',
    },
    {
      id: 'kyc-rebuild',
      title: 'SSO / SAML Authentication Rebuild',
      kind: 'tech',
      effort: 8,
      effortRevealed: 8,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'kyc-rebuild',
    },
    {
      id: 'automated-tests',
      title: 'Automated Test Suite',
      kind: 'tech',
      effort: 5,
      effortRevealed: 5,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'automated-tests',
    },
  ],

  discoveryPool: [
    {
      id: 'discovery-push-notifications',
      title: 'Smart Notification Controls (digest & quiet hours)',
      kind: 'customer',
      effort: 2,
      effortRevealed: 2,
      value: 200,
      satisfies: ['darren'],
      requires: [],
      productId: 'discovery-push-notifications',
    },
    {
      id: 'discovery-tax-export',
      title: 'Usage & Billing Export (CSV / invoicing)',
      kind: 'customer',
      effort: 6,
      effortRevealed: 6,
      value: 350,
      satisfies: ['maya', 'darren'],
      requires: [],
      productId: 'discovery-tax-export',
    },
    {
      id: 'discovery-education-center',
      title: 'In-Product Help Center & Tutorials',
      kind: 'customer',
      effort: 4,
      effortRevealed: 4,
      value: 300,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'discovery-education-center',
    },
    {
      id: 'discovery-auto-invest',
      title: 'Workflow Automations (scheduled triggers)',
      kind: 'customer',
      effort: 7,
      effortRevealed: 7,
      value: 450,
      satisfies: ['maya', 'priya'],
      requires: [],
      productId: 'discovery-auto-invest',
    },
    {
      id: 'discovery-market-data-cost',
      title: 'Infrastructure Cost Optimization',
      kind: 'tech',
      effort: 5,
      effortRevealed: 5,
      value: 0,
      satisfies: [],
      requires: [],
      productId: 'discovery-market-data-cost',
    },
  ],

  eventDeck: [
    {
      id: 'wei-crypto-demand',
      category: 'stakeholder',
      baseWeight: 0,
      trigger: 'forced',
      forcedAtIteration: 2,
      narrative:
        'Wei (VP Growth): "Ship an AI assistant by month-end — every competitor is announcing one." Your team has zero ML experience and the data-privacy story is unclear.',
      options: [
        {
          id: 'accept',
          label: 'Accept and commit',
          visibleConsequence: 'Leadership +2, morale −3, tech debt +10. New AI-assistant PBI injected.',
          effects: [
            { kind: 'trust', stakeholderId: 'hq', delta: 2 },
            { kind: 'morale', delta: -3 },
            { kind: 'tech-debt', delta: 10 },
            {
              kind: 'add-pbi',
              pbi: {
                id: 'event-crypto-tab',
                title: 'AI Assistant (exec mandate, data-privacy review)',
                kind: 'regulatory',
                effort: 14,
                effortRevealed: null,
                effortUncertain: true,
                value: 400,
                satisfies: ['priya'],
                requires: [],
                productId: 'event-crypto-tab',
              },
            },
          ],
        },
        {
          id: 'trade-off',
          label: 'Propose trade-off in writing',
          visibleConsequence: 'AI assistant OR self-serve onboarding. Leadership trust short-term −1.',
          effects: [{ kind: 'trust', stakeholderId: 'hq', delta: -1 }],
        },
        {
          id: 'defer',
          label: 'Defer with a plan',
          visibleConsequence: 'Leadership trust −2, team morale +2.',
          effects: [
            { kind: 'trust', stakeholderId: 'hq', delta: -2 },
            { kind: 'morale', delta: 2 },
          ],
        },
      ],
    },
    {
      id: 'ciro-social-warning',
      category: 'regulatory',
      baseWeight: 3,
      trigger: 'weighted',
      narrative:
        'Aisha flags the activity feed: @mentions leak data across tenant boundaries and would fail the SOC 2 review before the enterprise deal closes.',
      options: [
        {
          id: 'scope-down',
          label: 'Scope feature down; enforce tenant isolation',
          visibleConsequence: 'Security trust +2. Priya disappointed.',
          effects: [
            { kind: 'trust', stakeholderId: 'ciro', delta: 2 },
            { kind: 'happiness', customerId: 'priya', delta: -1 },
          ],
        },
        {
          id: 'compliance-review',
          label: 'Full security review before launch',
          visibleConsequence: 'Delay 1 iteration.',
          effects: [{ kind: 'capacity-baseline', delta: -2 }],
        },
        {
          id: 'ship-anyway',
          label: 'Ship anyway — "move fast"',
          visibleConsequence: 'Big compliance risk.',
          effects: [
            { kind: 'trust', stakeholderId: 'ciro', delta: -3 },
            { kind: 'tech-debt', delta: 10 },
          ],
        },
      ],
    },
    {
      id: 'qa-quits',
      category: 'team',
      baseWeight: 2,
      trigger: 'random',
      narrative:
        'Your QA engineer signals burnout and hints at leaving. Morale is shaky.',
      options: [
        {
          id: 'lighten-load',
          label: 'Lighten load; automate tests',
          visibleConsequence: 'Velocity short-term −2, long-term +.',
          effects: [
            { kind: 'morale', delta: 2 },
            { kind: 'capacity-baseline', delta: -1 },
          ],
        },
        {
          id: 'promote',
          label: 'Promote + raise',
          visibleConsequence: 'Morale +3. Budget hit.',
          effects: [{ kind: 'morale', delta: 3 }],
        },
        {
          id: 'ignore',
          label: 'Ignore it',
          visibleConsequence: 'Risk of quit.',
          effects: [{ kind: 'morale', delta: -2 }],
        },
      ],
    },
    {
      id: 'maya-churn-risk',
      category: 'customer',
      baseWeight: 3,
      trigger: 'weighted',
      narrative:
        'Maya has logged in twice in 3 weeks. Her trial survey: "No self-serve onboarding for my team, we are switching to Asana."',
      options: [
        {
          id: 'commit-tfsa',
          label: 'Publicly commit to self-serve onboarding by iter 4',
          visibleConsequence: 'Mid-market buy-in.',
          effects: [{ kind: 'happiness', customerId: 'maya', delta: 2 }],
        },
        {
          id: 'retention-campaign',
          label: 'Extend trial + discount instead',
          visibleConsequence: 'Temporary lift.',
          effects: [{ kind: 'happiness', customerId: 'maya', delta: 1 }],
        },
        {
          id: 'nothing',
          label: 'Do nothing',
          visibleConsequence: 'Maya churns.',
          effects: [{ kind: 'happiness', customerId: 'maya', delta: -3 }],
        },
      ],
    },
    {
      id: 'darren-reddit',
      category: 'customer',
      baseWeight: 2,
      trigger: 'random',
      narrative:
        'Darren posts a teardown on Hacker News comparing Hubflow to Linear. His verdict matters.',
      options: [
        {
          id: 'engage',
          label: 'PM engages publicly, acknowledges gaps',
          visibleConsequence: 'Priya interested; Darren appreciates candor.',
          effects: [
            { kind: 'happiness', customerId: 'darren', delta: 1 },
            { kind: 'happiness', customerId: 'priya', delta: 1 },
          ],
        },
        {
          id: 'deflect',
          label: 'Route to support; no comment',
          visibleConsequence: 'Opportunity missed.',
          effects: [{ kind: 'happiness', customerId: 'darren', delta: -1 }],
        },
      ],
    },
  ],
};
